# capability-probe.ps1
# Copyright (c) 2026 fidpa
# SPDX-License-Identifier: MIT
# https://github.com/fidpa/proxmox-gpu-passthrough
#
# Windows Guest GPU Capability Probe
#
# Purpose: Gather a complete, vendor-neutral snapshot of GPU capabilities
#          inside a Windows VM after passthrough is set up. Confirms that
#          the card is not just "detected" but actually functional for
#          DirectX, Vulkan, OpenGL, and hardware video decode/encode.
#
# How to run (from Proxmox host):
#   qm guest exec <vmid> -- powershell.exe -ExecutionPolicy Bypass -File capability-probe.ps1
#
# How to run (interactively in Windows):
#   powershell -ExecutionPolicy Bypass -File capability-probe.ps1
#
# What it checks:
#   - DirectX feature level, Adapter info, driver, VRAM
#   - Vulkan: ICD registration, supported version, device presence
#   - OpenGL: version, renderer
#   - Video decode/encode (DXVA2 / NVENC / QSV profiles)
#   - Adapter attributes (hardware-accelerated, driver model)
#
# Output: Structured text report. Redirect to a file for record keeping:
#   .\capability-probe.ps1 > capability-report.txt
#
# Why not rely on Device Manager?
#   Device Manager can show "this device is working" while Vulkan sees zero
#   devices (missing ICD registration) or DirectX is stuck on software
#   rendering (driver returned a degraded feature level). This script
#   probes each API independently to catch that class of silent failure.

$ErrorActionPreference = 'Continue'

function Write-Section($Title) {
    Write-Output ""
    Write-Output "=== $Title ==="
}

Write-Output "GPU Capability Probe"
Write-Output "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Output "Host:      $env:COMPUTERNAME"

# ---------------------------------------------------------------------------
Write-Section "1. GPU Adapter (WMI Win32_VideoController)"
try {
    Get-CimInstance Win32_VideoController | ForEach-Object {
        Write-Output "Name            : $($_.Name)"
        Write-Output "Driver Version  : $($_.DriverVersion)"
        Write-Output "Driver Date     : $($_.DriverDate)"
        Write-Output "Video Processor : $($_.VideoProcessor)"
        # WMI AdapterRAM is a 32-bit field. Tools show ~2 GB (signed int32) or ~4 GB
        # (unsigned uint32) depending on interpretation. NEVER trust this for VRAM on
        # any card with >2 GB VRAM. Use DXGI (section 3a below) or dxdiag (3b) instead.
        Write-Output "AdapterRAM (WMI): $($_.AdapterRAM)  [NOTE: 32-bit WMI field -> see section 3a DXGI for real VRAM]"
        Write-Output "Status          : $($_.Status)"
        Write-Output "Availability    : $($_.Availability)"
        Write-Output ""
    }
} catch {
    Write-Output "WMI query failed: $_"
}

# ---------------------------------------------------------------------------
Write-Section "2. PnP Device Status"
try {
    Get-PnpDevice -Class Display -Status OK -ErrorAction Stop | ForEach-Object {
        Write-Output "Friendly Name : $($_.FriendlyName)"
        Write-Output "Instance ID   : $($_.InstanceId)"
        Write-Output "Status        : $($_.Status)"
        Write-Output ""
    }
    # Look for problem codes (Code 43 etc.)
    $bad = Get-PnpDevice -Class Display | Where-Object { $_.Status -ne 'OK' }
    if ($bad) {
        Write-Output "WARNING: Display devices NOT OK:"
        $bad | ForEach-Object { Write-Output "  $($_.FriendlyName)  Status=$($_.Status)  Problem=$($_.Problem)" }
    }
} catch {
    Write-Output "PnP query failed: $_"
}

# ---------------------------------------------------------------------------
Write-Section "3a. VRAM via DXGI (authoritative, direct P/Invoke)"
# DXGI_ADAPTER_DESC1.DedicatedVideoMemory is the canonical source for real VRAM --
# no WMI 32-bit cap, no dxdiag dependency. On systems without DXGI this section
# silently falls through to 3b (dxdiag) below.
try {
    Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)]
public struct DXGI_ADAPTER_DESC1 {
    [MarshalAs(UnmanagedType.ByValTStr, SizeConst=128)] public string Description;
    public uint   VendorId;
    public uint   DeviceId;
    public uint   SubSysId;
    public uint   Revision;
    public UIntPtr DedicatedVideoMemory;
    public UIntPtr DedicatedSystemMemory;
    public UIntPtr SharedSystemMemory;
    public long   AdapterLuid;
    public uint   Flags;
}

// IDXGIFactory1 vtable layout after IUnknown (auto-generated by InterfaceIsIUnknown):
//   4x IDXGIObject     (SetPrivateData, SetPrivateDataInterface, GetPrivateData, GetParent)
//   5x IDXGIFactory    (EnumAdapters, Make/GetWindowAssociation, CreateSwapChain, CreateSoftwareAdapter)
//   1x IDXGIFactory1   (EnumAdapters1 — our target)
//   1x IDXGIFactory1   (IsCurrent — not used here)
// So: 9 placeholders, then EnumAdapters1.
[ComImport, Guid("770AAE78-F26F-4DBA-A829-253C83D1B387"),
 InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface IDXGIFactory1 {
    [PreserveSig] int _m00(); [PreserveSig] int _m01(); [PreserveSig] int _m02(); [PreserveSig] int _m03();
    [PreserveSig] int _m04(); [PreserveSig] int _m05(); [PreserveSig] int _m06(); [PreserveSig] int _m07();
    [PreserveSig] int _m08();
    [PreserveSig] int EnumAdapters1(uint i, out IntPtr pAdapter);
}

// IDXGIAdapter1 vtable layout after IUnknown:
//   4x IDXGIObject     (SetPrivateData, SetPrivateDataInterface, GetPrivateData, GetParent)
//   3x IDXGIAdapter    (EnumOutputs, GetDesc, CheckInterfaceSupport)
//   1x IDXGIAdapter1   (GetDesc1 — our target)
// So: 7 placeholders, then GetDesc1.
[ComImport, Guid("29038F61-3839-4626-91FD-086879011A05"),
 InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface IDXGIAdapter1 {
    [PreserveSig] int _m00(); [PreserveSig] int _m01(); [PreserveSig] int _m02(); [PreserveSig] int _m03();
    [PreserveSig] int _m04(); [PreserveSig] int _m05(); [PreserveSig] int _m06();
    [PreserveSig] int GetDesc1(out DXGI_ADAPTER_DESC1 pDesc);
}

public static class DxgiProbe {
    [DllImport("dxgi.dll")] public static extern int CreateDXGIFactory1(
        [In] ref Guid riid, out IntPtr ppFactory);
}
"@ -ErrorAction Stop

    # IID_IDXGIFactory1 per <dxgi.h>
    $iid     = [Guid]"770AAE78-F26F-4DBA-A829-253C83D1B387"
    $factPtr = [IntPtr]::Zero
    $hr      = [DxgiProbe]::CreateDXGIFactory1([ref]$iid, [ref]$factPtr)
    if ($hr -ne 0 -or $factPtr -eq [IntPtr]::Zero) {
        Write-Output "CreateDXGIFactory1 failed (hr=0x$($hr.ToString('X8'))). Falling through to dxdiag."
    } else {
        $factory = [Runtime.InteropServices.Marshal]::GetObjectForIUnknown($factPtr) -as [IDXGIFactory1]
        $i = 0
        while ($true) {
            $adapterPtr = [IntPtr]::Zero
            $hr = $factory.EnumAdapters1($i, [ref]$adapterPtr)
            if ($hr -ne 0 -or $adapterPtr -eq [IntPtr]::Zero) { break }
            $adapter = [Runtime.InteropServices.Marshal]::GetObjectForIUnknown($adapterPtr) -as [IDXGIAdapter1]
            $desc = New-Object DXGI_ADAPTER_DESC1
            [void]$adapter.GetDesc1([ref]$desc)
            $vramMB = [math]::Round($desc.DedicatedVideoMemory.ToUInt64() / 1MB, 0)
            $sharedMB = [math]::Round($desc.SharedSystemMemory.ToUInt64() / 1MB, 0)
            Write-Output ("Adapter {0}  : {1}" -f $i, $desc.Description)
            Write-Output ("  VendorId     : 0x{0:X4}  DeviceId: 0x{1:X4}" -f $desc.VendorId, $desc.DeviceId)
            Write-Output ("  DedicatedVRAM: {0} MB" -f $vramMB)
            Write-Output ("  SharedSystem : {0} MB" -f $sharedMB)
            [Runtime.InteropServices.Marshal]::ReleaseComObject($adapter) | Out-Null
            [Runtime.InteropServices.Marshal]::Release($adapterPtr) | Out-Null
            $i++
        }
        if ($i -eq 0) { Write-Output "DXGI enumerated zero adapters." }
        [Runtime.InteropServices.Marshal]::ReleaseComObject($factory) | Out-Null
        [Runtime.InteropServices.Marshal]::Release($factPtr) | Out-Null
    }
} catch {
    Write-Output "DXGI probe not available on this system: $($_.Exception.Message)"
    Write-Output "(section 3b dxdiag below provides a fallback)"
}

# ---------------------------------------------------------------------------
Write-Section "3b. DirectX / Adapter (via dxdiag, fallback + feature levels)"
# dxdiag remains the source for feature levels and DXVA2 GUIDs, and acts as
# a safety net when DXGI P/Invoke isn't available.
$dxdiagOut = Join-Path $env:TEMP "dxdiag_probe_$PID.txt"
try {
    Start-Process -FilePath dxdiag.exe -ArgumentList "/t", $dxdiagOut -Wait -WindowStyle Hidden
    # dxdiag writes asynchronously; wait for the file to settle
    $tries = 0
    while (-not (Test-Path $dxdiagOut) -and $tries -lt 30) {
        Start-Sleep -Milliseconds 500
        $tries++
    }
    if (Test-Path $dxdiagOut) {
        $content = Get-Content $dxdiagOut -Raw
        # Extract Display Devices section
        if ($content -match '(?s)Display Devices\s*-+\s*(.+?)(?:\r?\n-+|\z)') {
            $display = $matches[1].Trim()
            # Pull the most useful lines
            $keepers = @(
                'Card name', 'Manufacturer', 'Chip type', 'DAC type',
                'Dedicated Memory', 'Shared Memory', 'Current Mode',
                'Driver Version', 'Driver Model', 'Driver Date',
                'Feature Levels', 'Driver Type'
            )
            foreach ($k in $keepers) {
                $match = Select-String -InputObject $display -Pattern "^\s*$k\s*:\s*.+$" -AllMatches
                if ($match) {
                    $match.Matches | ForEach-Object { Write-Output $_.Value.Trim() }
                }
            }
        } else {
            Write-Output "(Could not parse Display Devices section)"
        }
    } else {
        Write-Output "dxdiag output not produced within timeout."
    }
} catch {
    Write-Output "dxdiag query failed: $_"
} finally {
    if (Test-Path $dxdiagOut) { Remove-Item $dxdiagOut -Force -ErrorAction SilentlyContinue }
}

# ---------------------------------------------------------------------------
Write-Section "4. Vulkan"
# Check ICD registration in registry
$vkReg = 'HKLM:\SOFTWARE\Khronos\Vulkan\Drivers'
if (Test-Path $vkReg) {
    $icds = Get-Item -Path $vkReg | Select-Object -ExpandProperty Property
    if ($icds.Count -eq 0) {
        Write-Output "WARNING: $vkReg exists but is EMPTY (no Vulkan ICDs registered)"
        Write-Output "         Intel Arc fix: create DWORD entry pointing to <driver>\igvk64.json with value 0"
    } else {
        foreach ($icd in $icds) {
            Write-Output "ICD Path : $icd"
            $val = (Get-ItemProperty -Path $vkReg -Name $icd).$icd
            Write-Output "Disabled : $val  (0 = enabled)"
        }
    }
} else {
    Write-Output "WARNING: $vkReg not present -- no Vulkan ICD registry key at all"
}

# Try vulkaninfo if available
$vkInfo = (Get-Command vulkaninfo -ErrorAction SilentlyContinue)
if ($vkInfo) {
    Write-Output ""
    Write-Output "vulkaninfo --summary:"
    & vulkaninfo --summary 2>&1 | Select-String -Pattern 'apiVersion|deviceName|driverName|driverInfo|Devices' | ForEach-Object {
        Write-Output "  $($_.Line.Trim())"
    }
} else {
    Write-Output "vulkaninfo.exe not found in PATH (install Vulkan SDK for full probe)"
}

# ---------------------------------------------------------------------------
Write-Section "5. OpenGL"
# Check for a GL renderer string. Windows ships no opengl-info by default;
# rely on a known tool if present, else skip gracefully.
$glTools = @('glxinfo.exe', 'opengl-info.exe', 'gpuinfo.exe')
$found = $null
foreach ($t in $glTools) {
    if (Get-Command $t -ErrorAction SilentlyContinue) { $found = $t; break }
}
if ($found) {
    Write-Output "Using: $found"
    & $found 2>&1 | Select-String -Pattern 'OpenGL (version|renderer|vendor)' | ForEach-Object {
        Write-Output "  $($_.Line.Trim())"
    }
} else {
    Write-Output "No OpenGL probe tool on PATH (optional -- install e.g. GPU Caps Viewer for details)"
}

# ---------------------------------------------------------------------------
Write-Section "6. Video Decode/Encode"
# NVIDIA: nvidia-smi
if (Get-Command nvidia-smi.exe -ErrorAction SilentlyContinue) {
    Write-Output "NVIDIA detected -- nvidia-smi:"
    & nvidia-smi.exe --query-gpu=name,driver_version,memory.total,encoder.sessions.active --format=csv 2>&1 | ForEach-Object {
        Write-Output "  $_"
    }
}
# Intel: search for iHD / Intel Media SDK
$intelQsv = Test-Path "$env:SystemRoot\System32\DriverStore\FileRepository\iigd_dch*"
if ($intelQsv) {
    Write-Output "Intel iGPU/dGPU driver store present -- QSV (Quick Sync Video) should be available"
}
# AMD: search for amdkmdap
$amdAmf = Test-Path "$env:SystemRoot\System32\DriverStore\FileRepository\c*amd*"
if ($amdAmf) {
    Write-Output "AMD driver store present -- AMF (Advanced Media Framework) should be available"
}

# ---------------------------------------------------------------------------
Write-Section "7. Summary"
Write-Output "Probe complete. Key follow-ups:"
Write-Output "  - 'AdapterRAM (WMI)' below 2 GB for a big GPU = WMI cap, not real VRAM."
Write-Output "  - 'DedicatedVRAM' (section 3a DXGI) is authoritative; dxdiag 'Dedicated Memory' is a fallback."
Write-Output "  - Vulkan ICD 'EMPTY'/'not present' = fix registry (Intel Arc common issue)."
Write-Output "  - PnP 'NOT OK' = driver problem; check Device Manager code."
Write-Output ""
Write-Output "Done."
